// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYNcURQB4rEEuIkVoAKBu9Ji52Y9PVh6s',
    appId: '1:657092912794:android:c615faaa716cffaafbe123',
    messagingSenderId: '657092912794',
    projectId: 'flutter-2024-aa0aa',
    storageBucket: 'flutter-2024-aa0aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6NCKFAGhcb9fDF1ZhfQts5du92PnAqFI',
    appId: '1:657092912794:ios:fd298ec329f14bbcfbe123',
    messagingSenderId: '657092912794',
    projectId: 'flutter-2024-aa0aa',
    storageBucket: 'flutter-2024-aa0aa.firebasestorage.app',
    androidClientId: '657092912794-splmstfit84p44tb176r1rc63a885n89.apps.googleusercontent.com',
    iosClientId: '657092912794-mrca87avjbns77qgcocfd42gj552j3b2.apps.googleusercontent.com',
    iosBundleId: 'com.LJRG.appvotacionesg10',
  );

}